# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: Instance Detection
short_description: Instance Detection
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: View the Real-world instance detection leaderboard here. For all metrics, higher number means better performance. We rank methods w.r.t the primary metric, i.e., AP.
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2024-04-01 08:00:00
end_date: 2024-06-02 07:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["AP", "AP50", "AP75", "AP_easy", "AP_hard", "AP_small", "AP_medium", "AP_large"],
        "default_order_by": "AP",
        "metadata": {
          "AP": {
            "sort_ascending": True,
            "description": "AP averages the precision over all instances at IoU threshold from 0.5 to 0.95 with the step size 0.05.",
          },
          "AP50": {
            "sort_ascending": True,
            "description": "AP50 is the precision averaged over all instances with IoU threshold as 0.5.",
          },
          "AP75": {
            "sort_ascending": True,
            "description": "AP75 is the precision averaged over all instances with IoU threshold as 0.75.",
          },
          "AP_easy": {
            "sort_ascending": True,
            "description": "AP_easy is the AP on <i>easy</i> scene images.",
          },
          "AP_hard": {
            "sort_ascending": True,
            "description": "AP_easy is the AP on <i>hard</i> scene images.",
          },
          "AP_small": {
            "sort_ascending": True,
            "description": "AP_easy is the AP on <i>small</i> object instances.",
          },
          "AP_medium": {
            "sort_ascending": True,
            "description": "AP_medium is the AP on <i>medium</i> object instances.",
          },
          "AP_large": {
            "sort_ascending": True,
            "description": "AP_hard is the AP on <i>hard</i> object instances.",
          },
          "AR": {
            "sort_ascending": True,
            "description": "AR averages the proposal recall at IoU threshold from 0.5 to 1.0 with the step size 0.05, regradless of the classification accuracy.",
          },
        }
      }

challenge_phases:
  - id: 1
    name: Dev Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: False
    is_public: True
    is_submission_public: True
    start_date: 2024-04-01 08:00:00
    end_date: 2024-06-02 07:59:59
    test_annotation_file: annotations/instance_annotations_devsplit.json
    codename: dev
    max_submissions_per_day: 5
    max_submissions_per_month: 30
    max_submissions: 30
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: TextAttribute
        description: Sample
        type: text
        required: False
      - name: SingleOptionAttribute
        description: Sample
        type: radio
        options: ["A", "B", "C"]
      - name: MultipleChoiceAttribute
        description: Sample
        type: checkbox
        options: ["alpha", "beta", "gamma"]
      - name: TrueFalseField
        description: Sample
        type: boolean
        required: True
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".json, .zip, .txt, .tsv, .gz, .csv, .h5, .npy, .npz"
  - id: 2
    name: Test Phase
    description: templates/challenge_phase_2_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2024-05-15 08:00:00
    end_date: 2024-06-02 07:59:59
    test_annotation_file: annotations/instance_annotations_testsplit.json
    codename: test
    max_submissions_per_day: 3
    max_submissions_per_month: 20
    max_submissions: 20
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: TextAttribute
        description: Sample
        type: text
      - name: SingleOptionAttribute
        description: Sample
        type: radio
        options: ["A", "B", "C"]
      - name: MultipleChoiceAttribute
        description: Sample
        type: checkbox
        options: ["alpha", "beta", "gamma"]
      - name: TrueFalseField
        description: Sample
        type: boolean
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False

dataset_splits:
  - id: 1
    name: Dev Split
    codename: dev_split
  - id: 2
    name: Test Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 2
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
